//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTeatroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoletoCompras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoletoCompras()
        {
            this.BoletoComprasFilas = new HashSet<BoletoComprasFilas>();
        }
    
        public int Id { get; set; }
        public string NombreCliente { get; set; }
        public int IdPresentacion { get; set; }
    
        public virtual Presentaciones Presentaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoletoComprasFilas> BoletoComprasFilas { get; set; }
    }
}
