//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTeatroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletos
    {
        public int Id { get; set; }
        public int IdPresentacion { get; set; }
        public string LetraFila { get; set; }
        public int IdBloqueFila { get; set; }
        public decimal Precio { get; set; }
        public int IdFactura { get; set; }
        public int NumAsiento { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Filas Filas { get; set; }
        public virtual Presentaciones Presentaciones { get; set; }
    }
}
