//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTeatroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precios
    {
        public int Id { get; set; }
        public decimal Precio { get; set; }
        public int IdProduccion { get; set; }
        public int IdBloque { get; set; }
    
        public virtual Bloques Bloques { get; set; }
        public virtual Producciones Producciones { get; set; }
    }
}
