//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTeatroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producciones()
        {
            this.Precios = new HashSet<Precios>();
            this.Presentaciones = new HashSet<Presentaciones>();
        }
    
        public int Id { get; set; }
        public string NombreObra { get; set; }
        public System.DateTime FechaInit { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Tipo { get; set; }
        public int IdTeatro { get; set; }
        public string Descripcion { get; set; }
        public int IdProduccionEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precios> Precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentaciones> Presentaciones { get; set; }
        public virtual ProduccionEstados ProduccionEstados { get; set; }
        public virtual Teatros Teatros { get; set; }
    }
}
