//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTeatroWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Usuario { get; set; }
        public string Password { get; set; }
        public int IdAcceso { get; set; }
        public long CedulaPersona { get; set; }
    
        public virtual Accesos Accesos { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
